#DB Configuration:
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/springBootTest
spring.datasource.username: root
spring.datasource.password: root

#JPA Configuration:
spring.jpa.database: mysql
spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update
server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1



